version: "3"

services:


  redis:
    build: ./docker/redis
    env_file: docker/redis/.env
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  neo4j:
    image: neo4j:4.3
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data


volumes:
  redis_data:
    driver: local
  neo4j_data:
